version: '3.8'

services:
  app:
    build:
      context: ./app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
